version: 0.0
resources:
  - search-photos:
      type: "AWS::Lambda::Function"
      properties:
        name: "search-photos"
        alias: "PROD"
        currentversion: "{{CURRENT}}"
        targetversion: "{{TARGET}}"

hooks: []
