version: 0.2

phases:
  build:
    commands:
      - cd search-photos && zip -r ../search-photos.zip . && cd ..
      - cp appspec-search.yml appspec.yaml
artifacts:
  files:
    - appspec.yaml
    - search-photos.zip
