version: 0.2

phases:
  install:
    commands:
      - echo "No dependencies to install for Lambdas"
  build:
    commands:
      - echo "Packaging search-photos…"
      - cd search-photos && zip -r ../search-photos.zip . && cd ..
      - echo "Packaging index-photos…"
      - cd index-photos && zip -r ../index-photos.zip . && cd ..
artifacts:
  files:
    - appspec.yml
    - search-photos.zip
    - index-photos.zip
