version: 0.2

phases:
  build:
    commands:
      - cd index-photos && zip -r ../index-photos.zip . && cd ..
      - cp appspec-index.yml appspec.yaml
artifacts:
  files:
    - appspec.yaml
    - index-photos.zip
